# Generated by Django 3.2.4 on 2021-12-27 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('first_name', models.TextField(default='')),
                ('last_name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.IntegerField(default=0)),
                ('physics', models.IntegerField(default=0)),
                ('chemistry', models.IntegerField(default=0)),
                ('biology', models.IntegerField(default=0)),
                ('english', models.IntegerField(default=0)),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.student')),
            ],
        ),
    ]
